<!-- 
	This WSDL implements the following CEMLIs I280(UpdatePersonJob) I352(DeleteEmplID) 
	I367(UpdateDepartment) I368(UpdateJobCode) Changes: 04/24/2017 - WSDL version 
	to 1.04 PMO-2345 - SOA - I280 - Add fault message to the WSDL PMO-2588 - 
	SOA - I352 - Add fault message to the WSDL PMO-2586 - SOA - I367 - Add fault 
	message to the WSDL PMO-2587 - SOA - I368 - Add fault message to the WSDL 
	Uncommented the policy references 

	Changes:
	04/24/2017 - WSDL version to 1.04
				 PMO-2345 - SOA - I280 - Add fault message to the WSDL
				 PMO-2588 - SOA - I352 - Add fault message to the WSDL
				 PMO-2586 - SOA - I367 - Add fault message to the WSDL
				 PMO-2587 - SOA - I368 - Add fault message to the WSDL
				 Uncommented the policy references
	
    03/02/2018 
    	Mukund Gidadhubli
	    	PMO-3540: I-280 WSDL requires the Date of Birth filed to contain a valid date.  When PeopleSoft is sending a blank date it violates the WSDL requirement and cause I-280 to fail.
	        Defect#10255: I280 (IDM - Person and Contingent Worker) - WSDL requires the Date of Birth filed to contain a valid date. When PeopleSoft is sending a blank date it violates the WSDL requirement and cause I-280 to fail.
	        Changes Made to this WSDL
	        	1. Created a new version of "../v1_04/UCIDMService_V1.04.wsdl" i.e., "../v1_04/UCIDMService_V1.05.wsdl"
	            2. Replaced "../../Schemas/v1_03/ServiceRequest_UpdatePersonJob_V1.03.xsd" with "../../Schemas/v1_04/ServiceRequest_UpdatePersonJob_V1.04.xsd" in the imports
				3. Removed duplicate referece to <wsp:Policy wsu:Id="UCPathService_SOAP_Fault_Policy"/>
	-->
<wsdl:definitions name="UCIDMService" targetNamespace="http://www.universityofcalifornia.edu/UCPath/IDM" 
xmlns:idm="http://www.universityofcalifornia.edu/UCPath/IDM" 
xmlns:ucpath="http://www.universityofcalifornia.edu/UCPath" 
xmlns:ucpfault="http://www.universityofcalifornia.edu/UCPath/UCPathFault"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" 
xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<wsdl:types>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath/IDM" schemaLocation="../../Schemas/v1_03/ServiceRequest_UpdateDepartment_V1.03.xsd"/>
		</xsd:schema>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath/IDM" schemaLocation="../../Schemas/v1_03/ServiceRequest_UpdateJobCode_V1.03.xsd"/>
		</xsd:schema>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath/IDM" schemaLocation="../../Schemas/v1_04/ServiceRequest_UpdatePersonJob_V1.04.xsd"/>
		</xsd:schema>
  		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath/IDM" schemaLocation="../../Schemas/v1_03/ServiceRequest_DeleteEmplID_V1.03.xsd"/>
		</xsd:schema>
		<xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath" schemaLocation="../../Schemas/v1_02/ServiceResponse_V1.02.xsd"/>
		</xsd:schema>
		    <xsd:schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import namespace="http://www.universityofcalifornia.edu/UCPath/UCPathFault" schemaLocation="../../Schemas/v1_03/UCPathFault.xsd" />
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="PersonJobRequest">
		<wsdl:part name="request" element="idm:UpdatePersonJobRequest"/>
	</wsdl:message>
	<wsdl:message name="PersonJobResponse">
		<wsdl:part name="response" element="ucpath:UCPathServiceResponse"/>
	</wsdl:message>

	<wsdl:message name="DepartmentRequest">
		<wsdl:part name="request" element="idm:UpdateDepartmentRequest"/>
	</wsdl:message>
	<wsdl:message name="DepartmentResponse">
		<wsdl:part name="response" element="ucpath:UCPathServiceResponse"/>
	</wsdl:message>

	<wsdl:message name="JobCodeRequest">
		<wsdl:part name="request" element="idm:UpdateJobCodeRequest"/>
	</wsdl:message>
	<wsdl:message name="JobCodeResponse">
		<wsdl:part name="response" element="ucpath:UCPathServiceResponse"/>
	</wsdl:message>

	<wsdl:message name="DeleteEmplIDRequest">
		<wsdl:part name="request" element="idm:DeleteEmplIDRequest"/>
	</wsdl:message>
	<wsdl:message name="DeleteEmplIDResponse">
		<wsdl:part name="response" element="ucpath:UCPathServiceResponse"/>
		</wsdl:message>
	<wsdl:message name="UCPathFault">
        <wsdl:part name="fault" element="ucpfault:UCPathFault"/>
    </wsdl:message>
	
	
	<wsdl:portType name="UCIDMServicePort">
		<wsdl:operation name="UpdatePersonJob">
			<wsdl:input message="idm:PersonJobRequest"/>
			<wsdl:output message="idm:PersonJobResponse"/>
			<wsdl:fault name="fault" message="idm:UCPathFault"/>
		</wsdl:operation>

		<wsdl:operation name="UpdateDepartment">
			<wsdl:input message="idm:DepartmentRequest"/>
			<wsdl:output message="idm:DepartmentResponse"/>
			<wsdl:fault name="fault" message="idm:UCPathFault"/>
		</wsdl:operation>

		<wsdl:operation name="UpdateJobCode">
			<wsdl:input message="idm:JobCodeRequest"/>
			<wsdl:output message="idm:JobCodeResponse"/>
			<wsdl:fault name="fault" message="idm:UCPathFault"/>
		</wsdl:operation>
		<wsdl:operation name="DeleteEmplID">
			<wsdl:input message="idm:DeleteEmplIDRequest"/>
			<wsdl:output message="idm:DeleteEmplIDResponse"/>
			<wsdl:fault name="fault" message="idm:UCPathFault"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="UCIDMServiceSOAP" type="idm:UCIDMServicePort">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsp:PolicyReference URI="#UCPathService_Msg_Protection_Policy" wsdl:required="false"/>

		<wsdl:operation name="UpdatePersonJob">
			<soap:operation soapAction="http://www.universityofcalifornia.edu/UCPath/IDM/UCIDMService/UpdateobPersonJob"/>
			<wsdl:input>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Input_Policy" wsdl:required="false"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Output_Policy" wsdl:required="false"/>
			</wsdl:output>
			<wsdl:fault name="fault">
          <soap:fault name="fault" use="literal"/>
      </wsdl:fault>
		</wsdl:operation>

		<wsdl:operation name="UpdateDepartment">
			<soap:operation soapAction="http://www.universityofcalifornia.edu/UCPath/IDM/UCIDMService/UpdateDepartment"/>
			<wsdl:input>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Input_Policy" wsdl:required="false"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Output_Policy" wsdl:required="false"/>
			</wsdl:output>
			<wsdl:fault name="fault">
                                <soap:fault name="fault" use="literal"/>
                        </wsdl:fault>
		</wsdl:operation>

		<wsdl:operation name="UpdateJobCode">
			<soap:operation soapAction="http://www.universityofcalifornia.edu/UCPath/IDM/UCIDMService/UpdateJobCode"/>
			<wsdl:input>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Input_Policy" wsdl:required="false"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Output_Policy" wsdl:required="false"/>
			</wsdl:output>
			<wsdl:fault name="fault">
                                <soap:fault name="fault" use="literal"/>
                        </wsdl:fault>
		</wsdl:operation>

		<wsdl:operation name="DeleteEmplID">
			<soap:operation soapAction="http://www.universityofcalifornia.edu/UCPath/IDM/UCIDMService/DeleteEmplID"/>
			<wsdl:input>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Input_Policy" wsdl:required="false"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#UCPathService_SOAP_Output_Policy" wsdl:required="false"/>
			</wsdl:output>
			<wsdl:fault name="fault">
                                <soap:fault name="fault" use="literal"/>
                        </wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	

	<wsp:Policy wsu:Id="UCPathService_SOAP_Input_Policy">
		<sp:SignedParts>
			<sp:Body />
			<sp:Header Namespace="http://www.w3.org/2005/08/addressing" />
			<sp:Header Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing" />
			<sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0" />
		</sp:SignedParts>
		<sp:EncryptedParts>
			<sp:Body />
			<sp:Header Name="fmw-context" Namespace="http://xmlns.oracle.com/fmw/context/1.0" />
		</sp:EncryptedParts>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UCPathService_SOAP_Output_Policy">
		<sp:SignedParts>
			<sp:Body />
		</sp:SignedParts>
		<sp:EncryptedParts>
			<sp:Body />
		</sp:EncryptedParts>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UCPathService_SOAP_Fault_Policy">
		<sp:SignedParts>
			<sp:Body />
		</sp:SignedParts>
		<sp:EncryptedParts>
			<sp:Body />
		</sp:EncryptedParts>
	</wsp:Policy>

	<wsp:Policy wsu:Id="UCPathService_Msg_Protection_Policy">
		<sp:AsymmetricBinding>
			<wsp:Policy>

				<sp:InitiatorToken>
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Always">
							<wsp:Policy>
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:InitiatorToken>

				<sp:RecipientToken>
					<wsp:Policy>
						<sp:X509Token
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Always">
							<wsp:Policy>
								<sp:WssX509V3Token10 />
							</wsp:Policy>
						</sp:X509Token>
					</wsp:Policy>
				</sp:RecipientToken>

				<sp:AlgorithmSuite>
					<wsp:Policy>
						<sp:Basic128 />
					</wsp:Policy>
				</sp:AlgorithmSuite>

				<sp:Layout>
					<wsp:Policy>
						<sp:Lax />
					</wsp:Policy>
				</sp:Layout>

				<sp:IncludeTimestamp />
				<sp:OnlySignEntireHeadersAndBody />
			</wsp:Policy>
		</sp:AsymmetricBinding>

		<sp:Wss10>
			<wsp:Policy />
		</sp:Wss10>
	</wsp:Policy>

	<wsdl:service name="UCIDMService">
		<wsdl:port binding="idm:UCIDMServiceSOAP" name="UCIDMServiceSOAP">
			<soap:address location="http://localhost:8080/UCPath/IDM/UCIDMService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>